In [1]:
import numpy as np
def VanderMatrix(vectorInput,increasing=True,N=0):
    if N==0:
        N = len(vectorInput)
    if increasing:
        return np.column_stack([x**(i) for i in range(N)])
    else:
         return np.column_stack([x**(N-1-i) for i in range(N)])

x = np.array([1, 2, 3, 5])

print("Vander Matrix Function with Increasing True: \n")
print(VanderMatrix(x))
print("\n Vander Matrix Function with Increasing False: \n")
print(VanderMatrix(x,False))

Vander Matrix Function with Increasing True: 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]

 Vander Matrix Function with Increasing False: 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
